controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

course_crud:
    path:       /{course}
    controller: App\Controller\CourseController::show
    requirements:
        page: '\d+'